### ISSUE TITLE
Redirect error

### ISSUE THREAD

**Issue by nanuxp** [mobilpay/Magento#33]
Hello,
Sometimes when customers press checkout button as Guest, the redirect is not being performed, cart gets emptied and order is saved in the database with status processing.
I found this coresponding error, in the logs:
main.ERROR: Notice: Undefined offset: 0 in/home/.../public_html/app/code/Netopia/Netcard/Controller/Payment/Redirect.php on line 81 [] [].

**After some testing, I was able to recreate the error. It is triggered when the customer checks "Create account" during checkout.**

**Comment by andreipanait** [comment]
Hello, thanks for raising this issue.

AFAIK by default Magento has no option to create an account during checkout, you either create it before or after [https://prnt.sc/1g3flt7](url). 

Are you by any chance using a plugin that alters this? If so, can you let us know which one? It would help us to have more details in order to recreate the error ourselves (Magento version, installed/active plugins, active theme, your shop URL).

Feel free to send any information you don't want to be publicly displayed via email to [implementare@netopia.ro](url)

**Comment by navid59** [comment]
Please, update the plugin & lets us know if there is any problem.
Thank you
